[build]
  publish = "frontend/dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

  # Weekly full anime data update
  [functions.scheduled-fetch]
    schedule = "0 0 * * 0"  # Every Sunday at midnight

  # Daily score updates
  [functions.update-scores]
    schedule = "0 0 * * *"  # Every day at midnight

  # Supabase keepalive ping
  [functions.keepalive]
    schedule = "0 */12 * * *"  # Every 12 hours