// src/genreIcons.js
import {
  faDragon,
  faMagic,
  faRunning,
  faHeartbeat,
  faSmile,
  faRobot,
  faTheaterMasks,
  faGhost,
  faBolt,
  faCoffee,
  faBrain,
  faBasketballBall,
  faLandmark,
  faMusic,
  faCogs,
  faFlag,
  faGlobe,
  faRocket,
  faMask,
  faChild,
  faBook,
  faCross,
  faGuitar,
  faUserSecret,
  faSchool,
  faPaw,
  faPalette,
  faLaugh,
  faCity,
  faClock,
  faBuilding,
  faCrown,
  faSearch,
  faMedal,
  faGamepad,
  faDumbbell,
  faHeartBroken,
  faCircle,
  faFilm,
  faMicrophone,
  faSyringe,
  faShip,
  faUserGraduate,
  faUserTie,
} from '@fortawesome/free-solid-svg-icons';

export const genreIcons = {
  // Genres
  Action: faRunning,
  Adventure: faDragon,
  "Avant Garde": faPalette,
  AwardWinning: faMedal,
  "Award Winning": faMedal,
  BoysLove: faHeartBroken,
  "Boys Love": faHeartBroken,
  Comedy: faSmile,
  Drama: faTheaterMasks,
  Fantasy: faMagic,
  GirlsLove: faHeartbeat,
  "Girls Love": faHeartbeat,
  Gourmet: faCoffee,
  Horror: faGhost,
  Mystery: faSearch,
  Romance: faHeartbeat,
  "Sci-Fi": faRobot,
  SciFi: faRobot,
  "Slice of Life": faCoffee,
  SliceOfLife: faCoffee,
  Sports: faBasketballBall,
  Supernatural: faMagic,
  Suspense: faBolt,

  // Themes
  "Adult Cast": faUserSecret,
  Anthropomorphic: faPaw,
  CGDCT: faSmile,
  Childcare: faChild,
  "Combat Sports": faDumbbell,
  Crossdressing: faMask,
  Delinquents: faCircle,
  Detective: faUserSecret,
  Educational: faBook,
  "Gag Humor": faLaugh,
  Gore: faGhost,
  Harem: faHeartbeat,
  "High Stakes Game": faGamepad,
  Historical: faLandmark,
  "Idols (Female)": faMicrophone,
  "Idols (Male)": faMicrophone,
  Isekai: faGlobe,
  Iyashikei: faCoffee,
  "Love Polygon": faHeartbeat,
  "Love Status Quo": faCircle,
  "Magical Sex Shift": faMagic,
  MahouShoujo: faMagic,
  MartialArts: faRunning,
  Mecha: faCogs,
  Medical: faSyringe,
  Military: faFlag,
  Music: faMusic,
  Mythology: faLandmark,
  "Organized Crime": faUserSecret,
  "Otaku Culture": faSmile,
  Parody: faSmile,
  "Performing Arts": faMicrophone,
  Pets: faPaw,
  Psychological: faBrain,
  Racing: faFlag,
  Reincarnation: faCircle,
  "Reverse Harem": faHeartbeat,
  Samurai: faCross,
  School: faSchool,
  Showbiz: faFilm,
  Space: faRocket,
  "Strategy Game": faGamepad,
  "Super Power": faBolt,
  Survival: faFlag,
  "Team Sports": faBasketballBall,
  "Time Travel": faClock,
  "Urban Fantasy": faCity,
  Vampire: faMask,
  "Video Game": faGamepad,
  Villainess: faUserSecret,
  "Visual Arts": faPalette,
  Workplace: faBuilding,

  // Demographics
  Josei: faUserTie,
  Kids: faChild,
  Seinen: faUserSecret,
  Shoujo: faGuitar,
  Shounen: faBook,
};
